Permission: # All permissions
  # Permission to hide the scoreboard
  Hide-Score: "lobby.hide"

scoreboard:
  title: "&6&lRANK UP"
  lines:
    - ""
    - "&1  %player_gamemode%"
    - ""
    - "&2  %player_is_op%"
    - ""
    - "&3  %player_ip%"
    - ""
    - "&ewww.site.com.br"
  # Tempo de atualização em segundos
  update-delay: 60