# Configuração da Scoreboard
scoreboard:
  title: "&6&lRANK UP"
  lines:
    - ""
    - "&fRank: &c%rank_prefix%"
    - "&fPontos: &7%rank_player_points%/%rank_next_cost%"
    - "%rank_next_progress_bar% %rank_next_progress%"
    - ""
    - "&fClan: &c%simpleclans_clan_tag%"
    - ""
    - "&fCoins: &e%vault_eco_balance_commas%"
    - "&fCash: &61.000"
    - ""
    - "&ewww.site.com.br"
  # Tempo de atualização em segundos
  update-delay: 60
  # World Black list:
  world-black-list:
    - exemple_world